
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_constructors_first: false
    public_member_api_docs: false
    invalid_use_of_protected_member: false
    avoid_dynamic_calls: false
    sort_pub_dependencies: false
    require_trailing_commas: false
    invalid_return_type_for_catch_error: false

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true