
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_constructors_first: false
    public_member_api_docs: false
    invalid_use_of_protected_member: false
    avoid_dynamic_calls: false
    invalid_return_type_for_catch_error: false

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true