name: store_compare

on:
  # Trigger the workflow on push
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    # Job name is Running Tests
    name: Tests
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.10.2'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter test --no-pub --coverage
      - run: bash <(curl -s https://codecov.io/bash) -t 76c8481b-2b56-49b7-b902-7e484c890b71

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.2'
          channel: 'stable'
      - run: flutter pub get
      - name: Analyze lib
        run: flutter analyze lib
      - name: Analyze test
        run: flutter analyze test